server:
  port: 8080
  #servlet上下文访问路径,默认/
  servlet:
    context-path: /im_bird_sys
spring:
  datasource:
    name: im_bird_sys
    #采用druid的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接数据库的url
    url: jdbc:mysql:///im_bird
    driver-class-name: com.mysql.cj.jdbc.Driver #8.0，多了一个cj
    #用户名
    username: root
    password: root
    #监控统计
    filters: stat
    initial-size: 2 #初始化连接
    max-idle: 10 #最大连接数目
    min-idle: 1 #最小空闲连接数
    max-active: 20 #最大活动连接数
    #获取连接超时的等待时间、
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-evit-runs-millis: 60000
    #一个连接池中最小生存空间
    min-evictable-time-millis: 30000
    #验证连接有效与否的SQL
    validation-query: SELECT 'x'
    #知名连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被池中去除掉
    test-while-idle: true
    #检出连接时不要测试，否则影响性能
    test-on-borrow: false


